apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daps-server.applicationSecret.name" . }}
  labels:
    {{- include "daps-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  ClientID: {{ .Values.secret.clientId | default (randAlphaNum 16) }}
  ClientSecret: {{ .Values.secret.clientSecret | default (randAlphaNum 16) }}
